Attempt #1 at updating catch script
Assets\Scripts\catchProjectile.cs(44,67): error CS0839: Argument missing

this error is only here until we add the fireball prefab to the game whenever the player is ready to throw the ball back.